### ISSUE TITLE
[Feature Request]: Add support for Model::fill()

### ISSUE THREAD

**Issue by LWlook** [ekvedaras/laravel-query-intellij#102]
**Feature Description**
I would like to have a possibility to have an autocompletion (with inspection "Unknown column") on the fill and forceFill methodes.

Is this already supported and I'm missing some settings, or isn't it implemented (for now  😉)?

**Comment by ekvedaras** [comment]
Not implemented. Might be that it just needs to be added to the method list.

**Comment by LWlook** [comment]
Wow, thanks for this fast response. Is that something witch I can add in the settings (like a setting "method list") or is this something which is coded?

**Comment by ekvedaras** [comment]
Needs to be added to the lists of this class https://github.com/ekvedaras/laravel-query-intellij/blob/main/src/main/kotlin/dev/ekvedaras/laravelquery/utils/LaravelUtils.kt 

you could try making a PR, otherwise I'll try to add it when I find some time. Just a warning that it will clash with [laravel-idea](https://laravel-idea.com/) as it already autocomplete on those methods.

**Comment by ekvedaras** [comment]
Actually, I see it should already autocomplete for the `fill` method. Just tested - it does. Could you share code snipped where it doesn't work + the model
